### ISSUE TITLE
Implement Dark Mode Toggle

### ISSUE THREAD

**Issue by abneribeiro** [abneribeiro/Abner_Portfolio#3]
## Problem

The absence of a dark mode option limits user customization and may impact usability, especially in low-light environments.

## Proposed Changes

1. **Dark Mode Toggle Implementation:** Add a toggle button to switch between light and dark modes, providing users with the option to customize the portfolio's appearance.

2. **Optimize Color Scheme for Dark Mode:** Ensure that the color scheme is optimized for readability and aesthetics in both light and dark modes.

## How to Contribute

1. Fork the repository.
2. Create a new branch: `git checkout -b implement-dark-mode`.
3. Integrate a dark mode toggle feature.
4. Test the toggle functionality across different browsers.
5. Submit a pull request with the dark mode implementation.

**Comment by Sabbirfeni** [comment]
Hi Abner,

Hope you are doing well. I have checked the issue and I am interested on adding the dark mode toggle feature with user readability and aesthetics.

Please assign this issue to me.

thanks,
Shabbir

**Comment by abneribeiro** [comment]
Hi Shabbir,

Thanks for your interest! I've assigned the dark mode toggle feature to you. Feel free to reach out if you have any questions or need assistance.

Best,
Abner

**Comment by Sabbirfeni** [comment]
Thank you much.

I will start to add freature as soon as I get back to my work.

Kinds,
Shabbir
